spring:
    profiles:
        active:
        - dev
---
spring: #开发环境
    profiles: dev
    application:
        name: microservicecloud-config-haopengyi-dev
---        
spring: #测试环境
    profiles: test
    application:
        name: microservicecloud-config-haopengyi-test

#格式为UTF-8